upgrade to TypeScript 3.5.0 (dev) to fix `readonly` bug (#3275)
* upgrade to TypeScript 3.5.0 (dev) to fix `readonly` bug

Fix at https://github.com/Microsoft/TypeScript/pull/30734 for an issue with TypeScript 3.4.x and use of `readonly T[]`, which causes webpack to report the following error:

```
TypeError: Cannot read property 'instantiations' of undefined
```

* remove use of toString method on generic type parameter (TS 3.5 rejects it)

```
../shared/src/util/memoizeObservable.ts:37:58 - error TS2339: Property 'toString' does not exist on type 'P'.
         const key = resolver ? resolver(params) : params.toString()
```