dev: Disable flaky ioutil lint check (#21846)
We're occasionally seeing this error:
./slack.go:105:19: undefined: io.ReadAll

It appears to be related to the internal/cmd/resources-report command
being compiled against an older version of Go that doesn't have the
io.ReadAll function yet.