add fake version of removeAllAtomically, with tests
The atomicity test fails (intentionally) because this version of
removeAllAtomically just calls os.RemoveAll.

=== RUN   Test_removeAllAtomically
--- FAIL: Test_removeAllAtomically (0.25s)
=== RUN   Test_removeAllAtomically/nonexistent_path_=>_no_error
    --- PASS: Test_removeAllAtomically/nonexistent_path_=>_no_error (0.00s)
=== RUN   Test_removeAllAtomically/removing_a_dir_makes_it_go_away
    --- PASS: Test_removeAllAtomically/removing_a_dir_makes_it_go_away (0.00s)
=== RUN   Test_removeAllAtomically/removing_a_big_dir_happens_atomically
    --- FAIL: Test_removeAllAtomically/removing_a_big_dir_happens_atomically (0.25s)
        cleanup_test.go:584: dir contains 887 items, want either the original count of 1000 or for it to be gone
FAIL