Revert "diff search: Don't duplicate hunk body in memory (#49859)" (#49864)
This reverts commit e4aa8814475603437bc77f539fe2c3fc28486656.

Seeing

```
--- FAIL: TestSearch/graphql_with_file_ranking (3.06s)
  | --- FAIL: TestSearch/graphql_with_file_ranking/Select_Queries (0.34s)
  | --- FAIL: TestSearch/graphql_with_file_ranking/Select_Queries/select_diffs_with_removed_lines_containing_pattern (0.05s)
  | search_test.go:1445: request GraphQL: rpc error: code = Unknown desc = bufio.Scanner: token too long
```