deduplicate CSS (#1588)
* deduplicate CSS

In `./web` and `./client/browser`, all Bootstrap CSS rules were duplicated in the output. This was because there were multiple .scss files that imported Bootstrap's CSS, and node-sass doesn't automatically dedupe. Removing those imports would prevent the files from using Bootstrap variables, so the imports need to remain.

This commit introduces optimize-css-assets-webpack-plugin, which uses cssnano to optimize away duplicate CSS rules.

Using `node-sass-import-once` used to work, but it no longer works (it does not actually eliminate duplicate imports); it is also unmaintained and other people have reported the same problem. `node-sass-once-importer` also does not work (it yields a completely empty CSS file).

* fix import of react-loading-spinner CSS

The @import was unnecessary because codeintellify already imports it.

The resolve.alias webpack config is necessary to avoid the following error (introduced by removing the old, deprecated import-once sass loader):

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../node_modules/@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css' in '/home/sqs/src/github.com/sourcegraph/sourcegraph/client/browser/src'
```

* fix color theme in browser extension

There is no color theme support in the browser extension, so this was unnecessary. This change is necessary to avoid hovers (Bootstrap `.card` class) from having a transparent background, a change likely introduced in the recent updates to the Bootstrap dep (4.0 -> 4.1).