Skip TestReaderCacheConcurrentRequests due to race condition
As discussed on Slack, when I run this locally as part of the whole test
suite (`go test ./...`) I get the following failure:

    --- FAIL: TestReaderCacheConcurrentRequests (0.00s)
        reader_cache_test.go:142: unexpected number of calls. want=1 have=2
    FAIL
    FAIL    github.com/sourcegraph/sourcegraph/enterprise/internal/codeintel/bundles/persistence/cache      0.128s