fix error in OSS build when hovering tokens
Fixes:

```
TypeError: Cannot read properties of undefined (reading 'fields')
    at API.hasStencils (api.ts:579:84)
```

Related to https://github.com/sourcegraph/sourcegraph/pull/43458, but that did not fully fix the issue (seemingly because the GitBlobLSIFData type is not even introspectible on OSS because LSIF is not available in OSS).