fix import of react-loading-spinner CSS
The @import was unnecessary because codeintellify already imports it.

The resolve.alias webpack config is necessary to avoid the following error (introduced by removing the old, deprecated import-once sass loader):

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../node_modules/@sourcegraph/react-loading-spinner/lib/LoadingSpinner.css' in '/home/sqs/src/github.com/sourcegraph/sourcegraph/client/browser/src'
```