suppress ResizeObserver type error
I was getting a weird TypeScript type error on a clean build.

```
$ pnpm -C client/web run build-ts
../testing/src/mockResizeObserver.ts:5:12 - error TS2339: Property 'ResizeObserver' does not exist on type 'never'.
```

Type-checking adds no value here anyway, and this is low risk to ignore.