remove use of toString method on generic type parameter (TS 3.5 rejects it)
```
../shared/src/util/memoizeObservable.ts:37:58 - error TS2339: Property 'toString' does not exist on type 'P'.
         const key = resolver ? resolver(params) : params.toString()
```