Fix `sg run-set enterprise` not starting on Linux
Before this change `sg run-set enterprise` would fail under Linux:

```
[enterprise-frontend] Failed to connect to codeintel database: DB not available: failed to connect to `host=127.0.0.1 user=mrnugget database=sourcegraph`: server error (FATAL: password authentication failed for user "mrnugget" (SQLSTATE 28P01))
--------------------------------------------------------------------------------
Failed to run enterprise-frontend: exited with 1
--------------------------------------------------------------------------------
error: failed to run enterprise-frontend
```

I suspect the reason it worked on macOS is that Postgres.app sets other
defaults (database name, user name, etc.)

In any case: it's good to make this explicit.