highlighting: use http.DetectContentType for detecting "text or binary" files
Prior to this change, these tests would fail:

```
--- FAIL: TestIsBinary (0.00s)
    --- FAIL: TestIsBinary/text_ISO-8859-1 (0.00s)
    	file_test.go:55: got true want false
    --- FAIL: TestIsBinary/text_UTF16_LE_with_BOM (0.00s)
    	file_test.go:55: got true want false
    --- FAIL: TestIsBinary/binary_nonsense (0.00s)
    	file_test.go:55: got false want true
```

After this change, we properly detect all of these as text/binary.

What this means for end-users is that:

1. Some binary files that previously rendered incorrectly as text no longer do.
2. Files with non-UTF8 encodings (ISO-8859-1, UTF16, etc., etc.) are now sent to the frontend and rendered as text, but note:
  - Syntax highlighting may not work on these files, since Syntect likely expects UTF8 input.
  - Code intelligence (hover, j2d, etc) will likely not work in such files, as the frontend also expects to only work with UTF8 input.
  - BUT you can at least view the file's contents, as you might in your editor or on GitHub.

---

Instead of:

![](https://user-images.githubusercontent.com/4569537/37877740-1e9399ca-3025-11e8-80fb-b7781e085f33.png)

You now get e.g.:

![image](https://user-images.githubusercontent.com/3173176/40696311-2aa23bee-637a-11e8-90b2-e854e3d92bbb.png)

---

Closes #8957
References sourcegraph/issues#51

correctly handle mimetypes that are not text/ prefixed but ARE valid text

remove if statement

update docs