internal/database: Sanitize error string before writing to last_error column in gitserver_repo  (#21334)
Without the fixes in this commit, the tests will now reproduce the error
reported in #19610.

```
$ go test -run TestSetLastError
--- FAIL: TestSetLastError (4.44s)
    gitserver_repos_test.go:271: setting last error: ERROR: invalid byte sequence for encoding "UTF8": 0x00 (SQLSTATE 22021)
    dbtest.go:85: DATABASE sourcegraph-test-7466609680094911369 left intact for inspection
FAIL
exit status 1
FAIL github.com/sourcegraph/sourcegraph/internal/database      4.447s
```

The error string can contain null terminated characters and we need to
remove them before writing to the last_error column of the
gitserver_repos table in the SetLastError method.

We add a function sanitizeToUTF8 that removes null characters as well
as sanitizes the string to a UTF-8 string. This commit updates all call sites
where last_error is being written to the DB by using the function first on the
input error string.

Additionally this commit includes some minor formatting fixes for affected
lines along with changes to simplifying the function signature of SetLastError.

Fixes #19610.

This was also reported in #20524.

Co-authored-by: Tomás Senart <tomas@sourcegraph.com>