upgrade to TypeScript 3.5.0 (dev) to fix `readonly` bug
Fix at https://github.com/Microsoft/TypeScript/pull/30734 for an issue with TypeScript 3.4.x and use of `readonly T[]`, which causes webpack to report the following error:

```
TypeError: Cannot read property 'instantiations' of undefined
```