sgx: improve error reporting of "src access" subcommands.
This change improves the error reporting of "src access" subcommands
significantly, providing the user with details on what they need to do in order
to fix the issue. We use the same approach in other gRPC failure situations, so
we reuse the same code to handle these errors.

Before:

```
$ src access list
   ERROR: rpc error: code = 16 desc = "RegisteredClients.ListUserPermissions requires auth"
```

After:

```
$ src access list
rpc error: code = 16 desc = "RegisteredClients.ListUserPermissions requires auth"

================================================================================
======== Your 'src' client is not authenticated with the remote server. ========
================================================================================

To authenticate with the server, run:

  src --endpoint=<url-to-sourcegraph-server> login

```

Same applies to all other `src access` subcommands (grant, list, etc) in all gRPC failure scenarios.