Without this change, the application fails to compile. With it, the linter gives an error.
Without this change:

```
$ yarn run build-ts
yarn run v1.22.4
$ tsc -b tsconfig.all.json
client/web/src/SourcegraphWebApp.tsx:323:35 - error TS2345: Argument of type '(state: Readonly<SourcegraphWebAppState>) => { globbing: boolean; searchCaseSensitivity: boolean; searchPatternType: SearchPatternType; viewerSubject: Pick<ISettingsSubject, "id" | "viewerCanAdminister">; copyQueryButton: boolean; showRepogroupHomepage: boolean; showOnboardingTour: boolean; showEnterpriseHomePanels: boolean; showMultilineSearchConsole: boolean; showSearchContext: boolean; showSearchContextManagement: boolean; showQueryBuilder: boolean; enableSmartQuery: boolean; enableCodeMonitoring: boolean; enableAPIDocs: boolean; settingsCascade: SettingsCascadeOrError<Settings>; authenticatedUser: Maybe<{ __typename: "User"; id: string; databaseID: number; username: string; avatarURL: Maybe<string>; email: string; displayName: Maybe<string>; siteAdmin: boolean; tags: string[]; url: string; settingsURL: Maybe<string>; viewerCanAdminister: boolean; organizations: { nodes: { id: string; name: string; displayName: Maybe<string>; url: string; settingsURL: Maybe<string>; }[]; }; session: { canSignOut: boolean; }; }>; }' is not assignable to parameter of type 'SourcegraphWebAppState | ((prevState: Readonly<SourcegraphWebAppState>, props: Readonly<SourcegraphWebAppProps>) => SourcegraphWebAppState | Pick<SourcegraphWebAppState, "error" | "authenticatedUser" | "settingsCascade" | "selectedSearchContextSpec" | "globbing" | "copyQueryButton" | "versionContext" | "showSearchContext" | "showSearchContextManagement" | "defaultSearchContextSpec" | "parsedSearchQuery" | "viewerSubject" | "navbarSearchQueryState" | "showMultilineSearchConsole" | "showQueryBuilder" | "enableSmartQuery" | "themePreference" | "availableVersionContexts" | "previousVersionContext" | "showRepogroupHomepage" | "showOnboardingTour" | "showEnterpriseHomePanels" | "enableCodeMonitoring" | "systemIsLightTheme" | "searchPatternType" | "searchCaseSensitivity" | "hasUserDefinedContexts" | "hasUserAddedRepositories"> | null) | Pick<SourcegraphWebAppState, "error" | "authenticatedUser" | "settingsCascade" | "selectedSearchContextSpec" | "globbing" | "copyQueryButton" | "versionContext" | "showSearchContext" | "showSearchContextManagement" | "defaultSearchContextSpec" | "parsedSearchQuery" | "viewerSubject" | "navbarSearchQueryState" | "showMultilineSearchConsole" | "showQueryBuilder" | "enableSmartQuery" | "themePreference" | "availableVersionContexts" | "previousVersionContext" | "showRepogroupHomepage" | "showOnboardingTour" | "showEnterpriseHomePanels" | "enableCodeMonitoring" | "systemIsLightTheme" | "searchPatternType" | "searchCaseSensitivity" | "hasUserDefinedContexts" | "hasUserAddedRepositories"> | null'.
  Type '(state: Readonly<SourcegraphWebAppState>) => { globbing: boolean; searchCaseSensitivity: boolean; searchPatternType: SearchPatternType; viewerSubject: Pick<ISettingsSubject, "id" | "viewerCanAdminister">; copyQueryButton: boolean; showRepogroupHomepage: boolean; showOnboardingTour: boolean; showEnterpriseHomePanels: boolean; showMultilineSearchConsole: boolean; showSearchContext: boolean; showSearchContextManagement: boolean; showQueryBuilder: boolean; enableSmartQuery: boolean; enableCodeMonitoring: boolean; enableAPIDocs: boolean; settingsCascade: SettingsCascadeOrError<Settings>; authenticatedUser: Maybe<{ __typename: "User"; id: string; databaseID: number; username: string; avatarURL: Maybe<string>; email: string; displayName: Maybe<string>; siteAdmin: boolean; tags: string[]; url: string; settingsURL: Maybe<string>; viewerCanAdminister: boolean; organizations: { nodes: { id: string; name: string; displayName: Maybe<string>; url: string; settingsURL: Maybe<string>; }[]; }; session: { canSignOut: boolean; }; }>; }' is not assignable to type '(prevState: Readonly<SourcegraphWebAppState>, props: Readonly<SourcegraphWebAppProps>) => SourcegraphWebAppState | Pick<SourcegraphWebAppState, "error" | "authenticatedUser" | "settingsCascade" | "selectedSearchContextSpec" | "globbing" | "copyQueryButton" | "versionContext" | "showSearchContext" | "showSearchContextManagement" | "defaultSearchContextSpec" | "parsedSearchQuery" | "viewerSubject" | "navbarSearchQueryState" | "showMultilineSearchConsole" | "showQueryBuilder" | "enableSmartQuery" | "themePreference" | "availableVersionContexts" | "previousVersionContext" | "showRepogroupHomepage" | "showOnboardingTour" | "showEnterpriseHomePanels" | "enableCodeMonitoring" | "systemIsLightTheme" | "searchPatternType" | "searchCaseSensitivity" | "hasUserDefinedContexts" | "hasUserAddedRepositories"> | null'.
    Type '{ globbing: boolean; searchCaseSensitivity: boolean; searchPatternType: SearchPatternType; viewerSubject: Pick<ISettingsSubject, "id" | "viewerCanAdminister">; copyQueryButton: boolean; showRepogroupHomepage: boolean; showOnboardingTour: boolean; showEnterpriseHomePanels: boolean; showMultilineSearchConsole: boolean; showSearchContext: boolean; showSearchContextManagement: boolean; showQueryBuilder: boolean; enableSmartQuery: boolean; enableCodeMonitoring: boolean; enableAPIDocs: boolean; settingsCascade: SettingsCascadeOrError<Settings>; authenticatedUser: Maybe<{ __typename: "User"; id: string; databaseID: number; username: string; avatarURL: Maybe<string>; email: string; displayName: Maybe<string>; siteAdmin: boolean; tags: string[]; url: string; settingsURL: Maybe<string>; viewerCanAdminister: boolean; organizations: { nodes: { id: string; name: string; displayName: Maybe<string>; url: string; settingsURL: Maybe<string>; }[]; }; session: { canSignOut: boolean; }; }>; }' is not assignable to type 'SourcegraphWebAppState | Pick<SourcegraphWebAppState, "error" | "authenticatedUser" | "settingsCascade" | "selectedSearchContextSpec" | "globbing" | "copyQueryButton" | "versionContext" | "showSearchContext" | "showSearchContextManagement" | "defaultSearchContextSpec" | "parsedSearchQuery" | "viewerSubject" | "navbarSearchQueryState" | "showMultilineSearchConsole" | "showQueryBuilder" | "enableSmartQuery" | "themePreference" | "availableVersionContexts" | "previousVersionContext" | "showRepogroupHomepage" | "showOnboardingTour" | "showEnterpriseHomePanels" | "enableCodeMonitoring" | "systemIsLightTheme" | "searchPatternType" | "searchCaseSensitivity" | "hasUserDefinedContexts" | "hasUserAddedRepositories"> | null'.
      Type '{ globbing: boolean; searchCaseSensitivity: boolean; searchPatternType: SearchPatternType; viewerSubject: Pick<ISettingsSubject, "id" | "viewerCanAdminister">; copyQueryButton: boolean; showRepogroupHomepage: boolean; showOnboardingTour: boolean; showEnterpriseHomePanels: boolean; showMultilineSearchConsole: boolean; showSearchContext: boolean; showSearchContextManagement: boolean; showQueryBuilder: boolean; enableSmartQuery: boolean; enableCodeMonitoring: boolean; enableAPIDocs: boolean; settingsCascade: SettingsCascadeOrError<Settings>; authenticatedUser: Maybe<{ __typename: "User"; id: string; databaseID: number; username: string; avatarURL: Maybe<string>; email: string; displayName: Maybe<string>; siteAdmin: boolean; tags: string[]; url: string; settingsURL: Maybe<string>; viewerCanAdminister: boolean; organizations: { nodes: { id: string; name: string; displayName: Maybe<string>; url: string; settingsURL: Maybe<string>; }[]; }; session: { canSignOut: boolean; }; }>; }' is missing the following properties from type 'Pick<SourcegraphWebAppState, "error" | "authenticatedUser" | "settingsCascade" | "selectedSearchContextSpec" | "globbing" | "copyQueryButton" | "versionContext" | "showSearchContext" | "showSearchContextManagement" | "defaultSearchContextSpec" | "parsedSearchQuery" | "viewerSubject" | "navbarSearchQueryState" | "showMultilineSearchConsole" | "showQueryBuilder" | "enableSmartQuery" | "themePreference" | "availableVersionContexts" | "previousVersionContext" | "showRepogroupHomepage" | "showOnboardingTour" | "showEnterpriseHomePanels" | "enableCodeMonitoring" | "systemIsLightTheme" | "searchPatternType" | "searchCaseSensitivity" | "hasUserDefinedContexts" | "hasUserAddedRepositories">': defaultSearchContextSpec, parsedSearchQuery, navbarSearchQueryState, themePreference, and 4 more.

323                     this.setState(state => ({
                                      ~~~~~~~~~~~
324                         settingsCascade,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
331                         viewerSubject: viewerSubjectFromSettings(settingsCascade, authenticatedUser),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
332                     }))
    ~~~~~~~~~~~~~~~~~~~~~~

Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

With it:

```
$ yarn run all:eslint
yarn run v1.22.4
$ DOCSITE_LIST="$(./dev/docsite.sh -config doc/docsite.json ls)" dev/foreach-ts-project.sh yarn -s run eslint --quiet
--- client/web: yarn -s run eslint --quiet
+ cd client/web
+ eval ' yarn -s run eslint --quiet'
++ yarn -s run eslint --quiet

/Users/slimsag/go/sourcegraph/client/web/src/SourcegraphWebApp.tsx
  306:13  error  Unused state field: 'enableAPIDocs'  react/no-unused-state

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How fun!

Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>